<script setup>
import { Head, Link, useForm } from '@inertiajs/vue3';
import AuthenticatedLayout from '../../Layouts/AuthenticatedLayout.vue';

const props = defineProps({ user: Object, roles: Array });
const form = useForm({ name: props.user?.name || '', email: props.user?.email || '', role: props.user?.role || '', status: props.user?.status || 'active', credential_delivery: 'invitation', password: '', password_confirmation: '' });
const submit = () => props.user ? form.put(`/users/${props.user.id}`) : form.post('/users');
</script>
<template>
    <Head :title="user ? 'Edit User' : 'Tambah User'" />
    <AuthenticatedLayout :title="user ? 'Edit User' : 'Tambah User'"><form class="max-w-xl rounded-xl border border-slate-200 bg-white p-6 shadow-sm" @submit.prevent="submit"><div class="flex items-center justify-between"><h1 class="text-xl font-semibold">{{ user ? 'Edit User' : 'Tambah User' }}</h1><Link href="/users" class="text-sm underline">Kembali</Link></div><label class="mt-5 block text-sm font-medium">Name<input v-model="form.name" class="mt-1 w-full rounded-lg border-slate-300" /></label><p v-if="form.errors.name" class="mt-1 text-sm text-red-600">{{ form.errors.name }}</p><label class="mt-4 block text-sm font-medium">Email<input v-model="form.email" type="email" class="mt-1 w-full rounded-lg border-slate-300" /></label><p v-if="form.errors.email" class="mt-1 text-sm text-red-600">{{ form.errors.email }}</p><label class="mt-4 block text-sm font-medium">Role<select v-model="form.role" class="mt-1 w-full rounded-lg border-slate-300"><option value="" disabled>Pilih role</option><option v-for="roleItem in roles" :key="roleItem.id" :value="roleItem.name">{{ roleItem.name }}</option></select></label><p v-if="form.errors.role" class="mt-1 text-sm text-red-600">{{ form.errors.role }}</p><template v-if="user"><label class="mt-4 block text-sm font-medium">Status<select v-model="form.status" class="mt-1 w-full rounded-lg border-slate-300"><option value="active">Active</option><option value="invitation_pending">Invitation pending</option><option value="disabled">Disabled</option></select></label></template><template v-else><fieldset class="mt-5"><legend class="text-sm font-medium">Credential user</legend><label class="mt-2 flex gap-2 text-sm"><input v-model="form.credential_delivery" value="invitation" type="radio" /> Kirim invitation email agar user membuat password sendiri</label><label class="mt-2 flex gap-2 text-sm"><input v-model="form.credential_delivery" value="temporary_password" type="radio" /> Tentukan password sementara tanpa email</label></fieldset><template v-if="form.credential_delivery === 'temporary_password'"><label class="mt-4 block text-sm font-medium">Password sementara<input v-model="form.password" type="password" class="mt-1 w-full rounded-lg border-slate-300" /></label><label class="mt-4 block text-sm font-medium">Konfirmasi password<input v-model="form.password_confirmation" type="password" class="mt-1 w-full rounded-lg border-slate-300" /></label><p v-if="form.errors.password" class="mt-1 text-sm text-red-600">{{ form.errors.password }}</p></template></template><button :disabled="form.processing" class="mt-6 rounded-lg bg-slate-900 px-4 py-2 text-sm text-white">Simpan user</button></form></AuthenticatedLayout>
</template>
